name: Jobs
version: 0.1-PreRELEASE
api: 5.0.0
main: SkulZOnTheYT\Jobs\Main
author: SkulZOnTheYT
depend: BedrockEconomy

commands:
  jobs:
    description: Jobs system
    aliases: [job, work]
    usage: "/jobs | /jobs leaderboard"