name: Jobs
version: 0.1
api: 5.0.0
main: SkulZOnTheYT\Jobs\Main
author: SkulZOnTheYT
depend: BedrockEconomy

commands:
  jobs:
    description: Jobs system main command
    usage: "/jobs"
    aliases: [job, pekerjaan, kerja]
    permission: jobs.command

permissions:
  jobs.command:
    description: "Allows players to use the /jobs command"
    default: true