# 🔧 Jobs Plugin Config

# Cooldown (in seconds) between switching jobs
jobSwitchCooldown: 3600   # default 1 jam

# Reward multipliers per job (base money before level scaling)
rewards:
  miner:
    money: 10
    exp: 5
  woodcutter:
    money: 8
    exp: 4
  fisher:
    money: 6
    exp: 3
  farmer:
    money: 5
    exp: 2

# Level system
level_up_exp: 100

# Job shop items
shop:
  fisher_lure:
    price: 500
    item: fishing_rod
  miner_torch:
    price: 300
    item: torch:16   # item:count format

# Leaderboard
leaderboard:
  top_limit: 10   # show top 10 players