# 🔧 Jobs Plugin Config

# Cooldown (in seconds) between switching jobs
jobSwitchCooldown: 3600   # default 1 jam

# Reward multipliers per job (base money before level scaling)
rewards:
  miner: 20
  woodcutter: 10
  farmer: 5
  fisher: 15

# XP gain per action
xp:
  miner: 5
  woodcutter: 3
  farmer: 2
  fisher: 4

# Level system
level:
  xp_required: 100   # base XP required to level up
  scaling: 1.0       # multiplier per level (1.0 = linear, >1 = harder each level)


# Job shop items
shop:
  fisher_lure:
    price: 500
    item: fishing_rod
  miner_torch:
    price: 300
    item: torch:16   # item:count format

# Leaderboard
leaderboard:
  top_limit: 10   # show top 10 players